#########################
# configuration section #
#########################

# Defines the location of the EZ-USB SDK
ZTEXPREFIX?=/opt/ztex

# The name of the jar archive
#JARTARGET=UCEcho.jar
# Java Classes that have to be build
#CLASSTARGETS=UCEcho.class
# Extra dependencies for Java Classes
#CLASSEXTRADEPS=

# ihx files (firmware ROM files) that have to be build
IHXTARGETS=usbfifo.ihx
# Extra Dependencies for ihx files
IHXEXTRADEPS=

# Extra files that should be included into the jar archive
#EXTRAJARFILES=ucecho.ihx fpga/ucecho.bin

################################
# DO NOT CHANAGE THE FOLLOWING #
################################
# Includes the main Makefile
include $(ZTEXPREFIX)/Makefile.mk
